services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5000:5000"
    environment:
      - API_GATEWAY_URL=http://api-gateway:8000
    depends_on:
      - api-gateway

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth:8001
      - PACIENTES_SERVICE_URL=http://ms-pacientes:8002
      - CITAS_SERVICE_URL=http://ms-citas:8003
      - HISTORIAL_SERVICE_URL=http://ms-historial:8004
    depends_on:
      - auth
      - ms-pacientes
      - ms-citas
      - ms-historial

  auth:
    build: ./services/auth
    container_name: auth
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite:////data/clinica.db
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - db-data:/data

  ms-pacientes:
    build: ./services/ms-pacientes
    container_name: ms-pacientes
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=sqlite:////data/clinica.db
    volumes:
      - db-data:/data

  ms-citas:
    build: ./services/ms-citas
    container_name: ms-citas
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=sqlite:////data/clinica.db
    volumes:
      - db-data:/data

  ms-historial:
    build: ./services/ms-historial
    container_name: ms-historial
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=sqlite:////data/clinica.db
    volumes:
      - db-data:/data

volumes:
  db-data:
